
# defines from file: ipc_control.h
MAX_MESSAGE_SIZE = 252
RSRC_STRING_LENGTH = 4
RSRC_OFFSET = 4
HEADER_LENGTH = 8
GET_METHOD = "GET"
PUT_METHOD = "PUT"
RSP_METHOD = "RSP"
STAT_RSRC = "STAT"
STOP_RSRC = "STOP"
STRT_RSRC = "STRT"
PAUS_RSRC = "PAUS"
RESU_RSRC = "RESU"
MODE_RSRC = "MODE"
OPTS_RSRC = "OPTS" #drill & game options: level, delay, speed, height can be changed on the fly
LCAM_RSRC = "LCAM" #left cam
RCAM_RSRC = "RCAM" #right cam
SCOR_RSRC = "SCOR" #player scores
IPCS_RSRC = "IPCS" #game IPC statistics
GAME_MODE_E = 1
DRILL_MODE_E = 2
WORKOUT_MODE_E = 3
ACTIVE_PARAM = "active"
SOFT_FAULT_PARAM = "sFault"
HARD_FAULT_PARAM = "hFault"
MODE_PARAM = "mode"
ID_PARAM = "id" #drill or workout ID
STEP_PARAM = "step" #drill step to execture
DOUBLES_PARAM = "doubles" #single or double mode
TIEBREAKER_PARAM = "tiebreaker"
SIM_MODE_PARAM = "z_sim" #used to set/clear simulation mode
LEVEL_PARAM = "level"
SPEED_PARAM = "speed"
DELAY_PARAM = "delay"
HEIGHT_PARAM = "height"
GRUNTS_PARAM = "grunts" # when enabled, Boomer grunts almost every time it throws a ball, in game or drill or workout mode.
POINTS_DELAY_PARAM = "ptDelay" #increase/decrease time between points in seconds
RUN_REDUCE_PARAM = "reduceRun" #reduce running
SERVE_MODE_PARAM = "wServes" #server for game: No Serves, All Serves, Alternative Serves
BOOMER_ALL_SERVES_E = 2
PLAYER_ALL_SERVES_E = 1
ALTERNATE_SERVES_E = 0
GAME_START_TIME = "time"
SERVER = "server"
BOOMER_SETS_PARAM = "b_sets"
PLAYER_SETS_PARAM = "p_sets"
BOOMER_GAMES_PARAM = "b_games"
PLAYER_GAMES_PARAM = "p_games"
BOOMER_POINTS_PARAM = "b_pts"
PLAYER_POINTS_PARAM = "p_pts"
BOOMER_TIEPOINTS_PARAM = "b_t_pts"
PLAYER_TIEPOINTS_PARAM = "p_t_pts"
IPC_0_NUM_READS_PARAM = "0_rd"
IPC_0_NUM_WRITES_PARAM = "0_wr"
IPC_0_NUM_BAD_PARAM = "0_bad"
IPC_1_NUM_READS_PARAM = "1_rd"
IPC_1_NUM_WRITES_PARAM = "1_wr"
IPC_1_NUM_BAD_PARAM = "1_bad"
NUM_CAM_CALIB_POINTS = 13
POINT_START_CHAR = 'a'
NUM_CAMERAS = 2
LEFT_CAM = 0
RIGHT_CAM = 1
RESP_OK = 200
BAD_REQUEST = 400 #used if the message decode fails
FORBIDDEN = 403
NOT_FOUND = 404 # unknown resource
METHOD_NOT_ALLOWED = 405
LOCKED = 423 # used for PUT mode if the boomer_base is Active
UNPROCESSABLE_ENTITY = 422 #used for encode errors - there was not a great error response for this
CTRL_TRANSPRT = 0
UI_TRANSPRT = 1
BASE_NAME = "Base"
CTRL_NAME = "Ctrl"
UI_NAME = "Ui"

# defines from file: global_parameters.h
LEVEL_MIN = 10
LEVEL_MAX = 70
LEVEL_DEFAULT = 20
LEVEL_STEP = 1 #Dave wants to be to change this at a finer scale than presented to a user
LEVEL_UI_STEP = 5
LEVEL_UI_FACTOR = 10 #the UI would divide the min/max/default & ui_step by this number to present to the user
SPEED_MIN = 80
SPEED_MAX = 120
SPEED_DEFAULT = 100
SPEED_STEP = 2
HEIGHT_MIN = -32
HEIGHT_MAX = 32
HEIGHT_DEFAULT = 0
HEIGHT_STEP = 2
DELAY_MIN = -2000
DELAY_MAX = 2000
DELAY_DEFAULT = 0
DELAY_STEP = 100
DELAY_UI_STEP = 100
DELAY_UI_FACTOR = 1000
