# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmessage.proto\"F\n\x0c\x62_status_msg\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x12\x12\n\nsoft_fault\x18\x02 \x01(\x08\x12\x12\n\nhard_fault\x18\x03 \x01(\x08\"w\n\nb_mode_msg\x12\x15\n\x04mode\x18\x01 \x01(\x0e\x32\x07.mode_e\x12\x18\n\x10\x64rill_workout_id\x18\x02 \x01(\x05\x12\x12\n\ndrill_step\x18\x03 \x01(\x05\x12\x0f\n\x07\x64oubles\x18\x04 \x01(\x08\x12\x13\n\x0btie_breaker\x18\x05 \x01(\x08\"K\n\x0c\x62_params_msg\x12\r\n\x05level\x18\x01 \x01(\x05\x12\r\n\x05speed\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05\x64\x65lay\x18\x04 \x01(\x05*<\n\x06mode_e\x12\x10\n\x0cMODE_UNKNOWN\x10\x00\x12\x08\n\x04GAME\x10\x01\x12\t\n\x05\x44RILL\x10\x02\x12\x0b\n\x07WORKOUT\x10\x03\x62\x06proto3'
)

_MODE_E = _descriptor.EnumDescriptor(
  name='mode_e',
  full_name='mode_e',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MODE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRILL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WORKOUT', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=287,
  serialized_end=347,
)
_sym_db.RegisterEnumDescriptor(_MODE_E)

mode_e = enum_type_wrapper.EnumTypeWrapper(_MODE_E)
MODE_UNKNOWN = 0
GAME = 1
DRILL = 2
WORKOUT = 3



_B_STATUS_MSG = _descriptor.Descriptor(
  name='b_status_msg',
  full_name='b_status_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='active', full_name='b_status_msg.active', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='soft_fault', full_name='b_status_msg.soft_fault', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hard_fault', full_name='b_status_msg.hard_fault', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=87,
)


_B_MODE_MSG = _descriptor.Descriptor(
  name='b_mode_msg',
  full_name='b_mode_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='b_mode_msg.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='drill_workout_id', full_name='b_mode_msg.drill_workout_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='drill_step', full_name='b_mode_msg.drill_step', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doubles', full_name='b_mode_msg.doubles', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tie_breaker', full_name='b_mode_msg.tie_breaker', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=208,
)


_B_PARAMS_MSG = _descriptor.Descriptor(
  name='b_params_msg',
  full_name='b_params_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='b_params_msg.level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed', full_name='b_params_msg.speed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='b_params_msg.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delay', full_name='b_params_msg.delay', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=285,
)

_B_MODE_MSG.fields_by_name['mode'].enum_type = _MODE_E
DESCRIPTOR.message_types_by_name['b_status_msg'] = _B_STATUS_MSG
DESCRIPTOR.message_types_by_name['b_mode_msg'] = _B_MODE_MSG
DESCRIPTOR.message_types_by_name['b_params_msg'] = _B_PARAMS_MSG
DESCRIPTOR.enum_types_by_name['mode_e'] = _MODE_E
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

b_status_msg = _reflection.GeneratedProtocolMessageType('b_status_msg', (_message.Message,), {
  'DESCRIPTOR' : _B_STATUS_MSG,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:b_status_msg)
  })
_sym_db.RegisterMessage(b_status_msg)

b_mode_msg = _reflection.GeneratedProtocolMessageType('b_mode_msg', (_message.Message,), {
  'DESCRIPTOR' : _B_MODE_MSG,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:b_mode_msg)
  })
_sym_db.RegisterMessage(b_mode_msg)

b_params_msg = _reflection.GeneratedProtocolMessageType('b_params_msg', (_message.Message,), {
  'DESCRIPTOR' : _B_PARAMS_MSG,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:b_params_msg)
  })
_sym_db.RegisterMessage(b_params_msg)


# @@protoc_insertion_point(module_scope)
