#!/usr/bin/env python3
"""
Sends stop/pause/resume message to boomer_base
"""
import logging
log_format = ('[%(asctime)s] %(levelname)-6s %(message)s')
logging.basicConfig(format=log_format, level=logging.INFO)
# logging.basicConfig(format=log_format, level=logging.DEBUG)


if __name__ == '__main__':
   from ctrl_messaging_routines import send_msg, is_state
   from control_ipc_defines import PUT_METHOD, STOP_RSRC, PAUS_RSRC, UI_TRANSPRT, base_state_e
   import sys

   # print("argv[0]: {}".format(sys.argv[0]))
   resource = None
   if "stop" in sys.argv[0]:
      resource = STOP_RSRC
   elif "pause" in sys.argv[0]:
      resource = PAUS_RSRC
   # elif "resume" in sys.argv[0]:
   #    resource = RESU_RSRC
   else:
      print("command not recognized: %s", sys.argv[0])
      sys.exit(1)

   rc, code = send_msg(PUT_METHOD, resource)
   if not rc:
      # the following logging is already performed by send_mgs
      # logging.error("PUT {} failed, code: {}".format(resource, code))
      sys.exit(1)

   if resource is STOP_RSRC:
      idle, state = is_state(state=base_state_e.IDLE.value)
      if (type(idle) is not bool):
         logging.error("GET Status failed")
         sys.exit(1)
      if idle:
         logging.info(f"Boomer state is '{state}")
      else:
         logging.error(f"Base isn't idle after stop command: state is '{state}'")
         sys.exit(1)
